# Generated by Django 4.1.3 on 2023-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0003_exercise_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
