# Generated by Django 4.1.3 on 2023-02-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='location',
        ),
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.TextField(default='afqwef'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='blog_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
