# Generated by Django 4.1.3 on 2022-12-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
